### ISSUE TITLE
Doesn't Work in Umbraco 7.3.0 (White Screen)

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/UmbracoBookshelf#21]
I installed a fresh copy of Umbraco 7.3.0 (currently, the latest version), Archetype 1.10 (currently, the latest version), and Bookshelf 0.10.4 (currently, the latest version). When I click an MD file, I see a white page:

![bookshelf](https://cloud.githubusercontent.com/assets/5933222/10214607/b90e7da2-67ce-11e5-986f-491d530c6153.png)

Note that I closed my browser, cleared my browser cache, deleted the Temp files, and recycle the app pool. Still see the issue.

Note that there are some other funky issues, but this is the biggest one.

**Comment by kgiszewski** [comment]
@Nicholas-Westby I tried the release candidate a few weeks ago and discovered the same thing. This commit: https://github.com/kgiszewski/UmbracoBookshelf/commit/d47805349066cd8f0235a3e29b7c3a495fc7d671 was one fix and I have to add another that addresses this: http://issues.umbraco.org/issue/U4-7033

I'm hoping to get a patched version out soon.

**Comment by kgiszewski** [comment]
I have to re-review my commits and test again since I'm not sure if additional changes to the core may have affected things.

**Comment by kgiszewski** [comment]
@Nicholas-Westby I just released a new version to deal with v7.3 changes. https://github.com/kgiszewski/UmbracoBookshelf/releases/tag/v0.10.5

**Comment by Nicholas-Westby** [comment]
@kgiszewski FYI, that fixed part of the problem. However, it seems that the white screen still displays when you click on the folder that contains a README.md. If I inspect the DOM and add a "display: block" to one of the elements (as your fix did for files), I can see the content.

**Comment by kgiszewski** [comment]
Fun ;) (not really). Ok I'll try to replicate and fix soon. If you have pointers on where you added the style it might help me :)

**Comment by kgiszewski** [comment]
Found it, releasing a new version (again). Thanks for reporting. :+1:
