### ISSUE TITLE
Installed package not accessible from backoffice

### ISSUE THREAD

**Issue by sbatty** [kgiszewski/UmbracoBookshelf#25]
I've installed the package through the backoffice and the package shows up under installed packages but there is not a tab in the backoffice to access the bookshelf as shown in the screenshots. The UmbracoBookshelf folder and contents are present under App_Plugins and also at the root. How do I access the bookshelf?

**Comment by kgiszewski** [comment]
Go to the users section and tick the box for the Bookshelf section.

**Comment by sbatty** [comment]
Umm. Wow, that was simple. Might not hurt to put a sentence in the Readme reminding new users of that.
Thank you.

**My apologies, I found the install note on our.umbraco which did direct users to enable the section. Just didn't find it on Github.**
