### ISSUE TITLE
Bookshelf does not work with Umbraco 7.6

### ISSUE THREAD

**Issue by JohnBergman** [kgiszewski/UmbracoBookshelf#26]
After upgrading a 7.5.13 instance.

Could not load all types from "UmbracoBookshelf, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping: . System.TypeLoadException on UmbracoBookshelf.Controllers.UmbracoBookshelfTreeController: Method 'get_FileSystem' in type 'UmbracoBookshelf.Controllers.UmbracoBookshelfTreeController' from assembly 'UmbracoBookshelf, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
It looks like the FileSystem property is an abstract property in the base class that the UmbracoBookshelfTreeController inherits from.

**Comment by dinc5150** [comment]
Just a quick report that I'm seeing this with the sites that I've upgraded too.

**Comment by dawoe** [comment]
It seems that a breaking change in the FileSystemTreeController in v7.6 
https://github.com/umbraco/Umbraco-CMS/commit/a9c7a7a405c735b0da188314de67822397fd06f2#diff-0f9f07a0d8fe412699f8d7912257cf2a

**Comment by kgiszewski** [comment]
Indeed. I'm not likely to fix this. I'd accept a PR or you may wanna fork this repo.

**Comment by dawoe** [comment]
This will require a seperate bookshelf version specific for v7.6.x. Is that okay by you ?

**Comment by JohnBergman** [comment]
I don't see any other way around it...

**Comment by kgiszewski** [comment]
If the Core version is changed to 7.6, then Bookshelf altered to use it; it should work. The nuget dependency also should be updated to use 7.6.

**Comment by kgiszewski** [comment]
Start with updating these two:

https://github.com/kgiszewski/UmbracoBookshelf/blob/master/config/package.nuspec#L15

https://github.com/kgiszewski/UmbracoBookshelf/blob/master/src/packages.config#L25

**Comment by blachawk** [comment]
I too would like to see this working on Umbraco 7.6.  Had this same experience today in trying to install it.

**Comment by kgiszewski** [comment]
Hey guys, I think I may have fixed this issue: https://github.com/kgiszewski/UmbracoBookshelf/releases/tag/v0.11.0

Please giver a test drive.
